# Generated by Django 2.2.2 on 2019-12-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='语言名')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('create_time', models.DateField(verbose_name='发布时间')),
            ],
        ),
    ]
