# Generated by Django 2.2.2 on 2019-12-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='author',
            field=models.CharField(max_length=30, verbose_name='作者'),
        ),
    ]
